### ISSUE TITLE
Can footer be floating, fixed at the bottom of the page

### ISSUE THREAD

**Issue by nicholst** [incf-nidash/nidmresults-spmhtml#15]
I just saw some example code on the web that shows it's really easy to make a floating footer at the bottom of the page.  As there might be *lots* of foci/clusters, it would be nice if the footer wasn't lost far off at the bottom of the page.  

Here's the example: http://jsfiddle.net/ZsnuZ/

I think it would be really easy to impliment.  What do you think @TomMaullin @cmaumet ?

**Comment by cmaumet** [comment]
This is nice and does look easy to implement!

@TomMaullin: the css style for the `footer` could be included in the header of the html template: https://github.com/incf-nidash/nidmresults-spmhtml/blob/master/spm_results.tpl#L10-L18.

**Comment by cmaumet** [comment]
@TomMaullin: I believe this is now implemented. Can you close this issue if it is indeed the case?

**Comment by cmaumet** [comment]
T
