### ISSUE TITLE
Displaying multiple excursion sets

### ISSUE THREAD

**Issue by TomMaullin** [incf-nidash/nidmresults-spmhtml#21]
The viewer currently only displays information from one contrast, or worse a mixture of information from several. It should create multiple HTML's, one for each contrast.

**Comment by cmaumet** [comment]
Thanks for creating this issue. I think we should focus on *excursion sets* (e.i. thresholded statistics) rather than contrast. This will ensure that we only display contrasts for which we have results available.

**Comment by TomMaullin** [comment]
Yes, I agree. That makes a lot more sense.

**Comment by cmaumet** [comment]
This was fixed in #24.
