### ISSUE TITLE
Testing on Travis CI (using Octave)

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-spmhtml#30]
To ease further developments, we should start using continuous integration to automate testing. I would recommend [Travis CI](https://travis-ci.org/) as we already have experience with it.

**Comment by cmaumet** [comment]
@TomMaullin: would you like to have a look into this?

**Comment by cmaumet** [comment]
Once we have this in place, the review process for the PRs should be much lighter!

**Comment by TomMaullin** [comment]
Do we still plan on this?

**Comment by cmaumet** [comment]
Yes :) I have started looking into this in the SPM-NIDM repo: https://github.com/incf-nidash/nidmresults-spm/pull/46. I'll add more info here once we have settled on how to implement this.

**Comment by cmaumet** [comment]
This is now WIP at: https://github.com/incf-nidash/nidmresults-spmhtml/pull/37

**Comment by TomMaullin** [comment]
This issue has now been resolved by PR #37
