### ISSUE TITLE
README update - remove note for developers

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-spmhtml#31]
Hi @TomMaullin,

Do you think the 'Notes for future development' could be moved to the 'Wiki' or as 'Projects' rather than directly in the README. I view the README as documentation for users/early adopters while more advanced information for developers could live in the 'Wiki' pages or the 'Projects' tabs.

Let me know how you feel about this! 

Camille

**Comment by TomMaullin** [comment]
This sounds good to me! Where can I find the 'Wiki'/'Projects'?

**Comment by cmaumet** [comment]
There are links at the top of any repo, more info in the doc:
 - GitHub wiki: https://help.github.com/articles/about-github-wikis/
 - GitHub projects: https://help.github.com/articles/about-project-boards/

You should already have write access for the wiki, let me know if you have troubles accessing Projects.

**Comment by TomMaullin** [comment]
This has now been moved to the wiki as requested.
