### ISSUE TITLE
Command-line compatibility

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-spmhtml#33]
We should add a condition to enable running the viewer in command-line mode. This condition would be used when SPM is requested to run in command-line mode (i.e. `defaults.cmdline = 1`). In that case, the viewer should not display the HTML page (only save the view in a file).

(This should help with testing on Travis CI, as the current version of the Octave/Spm Docker image is not set up for opening GUIs.)

**Comment by cmaumet** [comment]
@TomMaullin: This is not urgent but when you have some time do you think you could prioritize this issue? Once this is done, I should then be able to address #30.

**Comment by TomMaullin** [comment]
@cmaumet Ah yes, sorry! I'm currently halfway through sorting #32 but can change to do this first if you would like!

**Comment by cmaumet** [comment]
No rush. That's okay. Just let me know and I'll add 'continuous integration' to this repo.

**Comment by TomMaullin** [comment]
Hi @cmaumet, I was just wondering if perhaps you would be able to give an example in which defaults.cmdline is used in the SPM source code. I cannot seem to find it anywhere.

**Comment by cmaumet** [comment]
Sure! Searching in the SPM codebase: the call is `spm('CmdLine')`. The usage is described in spm.m at https://github.com/spm/spm12/blob/a3985071b47ca3f3d50752321edca37e31b977be/spm.m#L217-L223.

**Comment by TomMaullin** [comment]
This issue was addressed by PR #35
