### ISSUE TITLE
Re-running the viewer should ask to overwrite previous html folder

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-spmhtml#5]
If I run the viewer a first time with:

```
nidm_results_display(fullfile(fileparts(which('nidm_results_display')), 'Data', 'nidm.json'))
```

As expected, I get an `html` folder containing the `.html` file and the `.png` images:
![screen shot 2016-10-07 at 10 03 39](https://cloud.githubusercontent.com/assets/5374264/19184500/5c18db0c-8c75-11e6-9e9e-d68c1093dfaf.png)

Now, if I run the same command again, a new set of files is created in the same `html` folder with a `_002` suffix:
![screen shot 2016-10-07 at 10 04 40](https://cloud.githubusercontent.com/assets/5374264/19184521/7e48c8e0-8c75-11e6-8d5a-828fc7af833a.png)

We might want to ask the user if he/she wants to overwrite the `html` folder and if not, maybe display the files already available.

**Comment by TomMaullin** [comment]
How would you like it to ask the user? Via an interface or simply in the command line? Or maybe as an agument to the function?

ie `nidm_results_display(fullfile(fileparts(which('nidm_results_display')), 'Data', 'nidm.json'), 'overWrite')` could overwrite the folder whereas `nidm_results_display(fullfile(fileparts(which('nidm_results_display')), 'Data', 'nidm.json'), 'noverWrite')` could do what the function is currently doing?

**Comment by TomMaullin** [comment]
This issue had been made redundant as the HTML folder no longer exists.
