### ISSUE TITLE
Generate Maximum Intensity Projection (MIP) image

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-spmhtml#8]
As discussed with @nicholst, @TomMaullin, we will need to generate the MIP image when missing (e.g. for NIDM-Results packs generated by FSL).

**Comment by cmaumet** [comment]
I think this was fixed by #11. @TomMaullin: can you close this issue?

**Comment by TomMaullin** [comment]
@cmaumet I don't think we ever resolved the problem with the units matrices so I'm not sure...

**Comment by cmaumet** [comment]
That's fine, we will check that with Guillaume when we have a chance.
